# Generated by Django 6.0.5 on 2026-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
