# Generated by Django 6.0.5 on 2026-05-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_create_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
