# Generated by Django 6.0.5 on 2026-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_head_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_image",
            field=models.FileField(blank=True, upload_to="blog/files/%Y/%m/%d/"),
        ),
    ]
