# Generated by Django 6.0.5 on 2026-05-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_file_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="file_image",
            new_name="file_upload",
        ),
    ]
