# Generated by Django 6.0.5 on 2026-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_file_image_post_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
