# Generated by Django 6.0.5 on 2026-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
